// Code generated by 'make generate'. DO NOT EDIT
package layers

// Template: Inputs of layers. Typically a list of `Layer`s.
type inputsTemplate interface {
	Iterator() <-chan Layer
	Count() int
}

type InputsBuilder struct {
	data      []Layer
	finalized bool
}

func (impl *InputsBuilder) Count() int {
	if !impl.finalized {
		panic("The Build should be called first.")
	}
	return len(impl.data)
}

func (impl *InputsBuilder) Iterator() <-chan Layer {
	if !impl.finalized {
		panic("The Build should be called first.")
	}
	c := make(chan Layer)
	go func() {
		for _, item := range impl.data {
			c <- item
		}
		close(c)
	}()
	return c
}

func (impl *InputsBuilder) Append(item Layer) {
	impl.data = append(impl.data, item)
}

func (impl *InputsBuilder) Build() {
	if impl.finalized {
		panic("The Build should not be called twice.")
	}
	impl.finalized = true
}
