// DO NOT EDIT. Generated by 'make generate'
package layers

// Inputs of layers. Typically a list of `Layer`s.
type Inputs interface {
	Iterator() <-chan Layer
}

type inputsImpl struct {
	data []Layer
}

func (impl *inputsImpl) Iterator() <-chan Layer {
	c := make(chan Layer)
	go func() {
		for _, item := range impl.data {
			c <- item
		}
	}()
	return c
}

func (impl *inputsImpl) Append(item Layer) {
	impl.data = append(impl.data, item)
}
